### ISSUE TITLE
scikit-fuzzy vs fuzzylogic

### ISSUE THREAD

**Issue by rayguang** [amogorkon/fuzzylogic#13]
Hello, thanks for this great tool. I would like to know the key differences between scikit-fuzzy and fuzzylogic. It appears to me both tools are good but scikit-fuzzy seems a bit more intuitive when building the rules

**Comment by amogorkon** [comment]
Hi,
thanks for your interest in fuzzylogic! Your question flatters me :) I'll try my best to answer it.

I guess one key difference is that I've built fuzzylogic solely for my own aspiration and to "get it right" in python, which, obviously, is quite different from the origin of scikit-fuzzy as a scientific library. 
From what I've seen so far of scikit-fuzzy, I honestly think fuzzylogic is easier to work and experiment with. I've looked at some examples for scikit-fuzzy and was baffled at how clumsy and inelegant some things are realized. My guess is, that might be because scikit-fuzzy is much older than fuzzylogic and didn't have the chance to adopt some of the python3 goodness yet or maybe they never tried to push the boundaries of python syntax?
Also, for me there never was a reason to implement simulation stuff in fuzzylogic thus far, so those parts surely are lacking, if you are interested in that.

Since you mentioned the rules specifically, I will have to agree with you on that. I've only added this part recently in close feedback with a guy who wants to use fuzzylogic for a facility HVAC system. Scikit-fuzzy offered some inspiration for how to realize this part, but I definitely haven't reached feature-parity with scikit-fuzzy there yet.

If you need anything in particular to realize what you want that fuzzylogic can't do yet, I'd be happy to discuss and add features to make it more useful.

**Comment by amogorkon** [comment]
Btw, it is now possible to describe rules with two input variables via tables using pandas. Input either be text tables, excel, etc. anything pandas supports, which should make it really easy to use in most practical cases. If more input variables are needed, "classic" Rules still can be used and both approaches can be freely combined.
